config/routes.rb
Rails.application.routes.draw do

  localesRegexp = /#{I18n.available_locales.join('|')}/

  root 'home#index'

  scope '(:locale)', locale: localesRegexp do
    get '/', to: 'home#index', as: :localized_root

    namespace :admin do
      resources :initiatives
      resources :ngos
      resources :users
    end

    resources :ngos, only: [:index, :show] do
      resources :initiatives, only: [:index, :show]
    end

    resources :initiatives, only: [] do
      resource :sign, only: [:create], controller: :initiative_signs do
        get 'count', on: :collection
      end
    end

    resources :users, only: [:new, :create], path_names: {new: :signup} do
      get 'validate/:token', on: :collection, to: :validate, as: :validate
    end

    resource :session, only: [:new, :create, :destroy]
  end

  namespace :api do
    resources :ngos, only: [:show, :update]
    resources :initiatives, only: [:show]
  end

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  belongs_to :ngo
  has_many :signs, class_name: 'InitiativeSign'
  validates :title, presence: true

  def self.random_initiatives(quantity = 5)
    self.order('RANDOM()').limit(quantity)
  end

end

app/controllers/admin/initiatives_controller.rb
class Admin::InitiativesController < ApplicationController
  before_action :set_initiative, only: [:show, :edit, :update, :destroy]

  # GET /initiatives
  # GET /initiatives.json
  def index
    @initiatives = Initiative.all
  end

  # GET /initiatives/1
  # GET /initiatives/1.json
  def show
  end

  # GET /initiatives/new
  def new
    @initiative = Initiative.new
  end

  # GET /initiatives/1/edit
  def edit
  end

  # POST /initiatives
  # POST /initiatives.json
  def create
    @initiative = Initiative.new(initiative_params)

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to admin_initiative_path(@initiative), notice: 'Initiative was successfully created.' }
        format.json { render :show, status: :created, location: admin_initiative_path(@initiative) }
      else
        format.html { render :new }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initiatives/1
  # PATCH/PUT /initiatives/1.json
  def update
    respond_to do |format|
      if @initiative.update(initiative_params)
        format.html { redirect_to admin_initiative_path(@initiative), notice: 'Initiative was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_initiative_path(@initiative) }
      else
        format.html { render :edit }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiatives/1
  # DELETE /initiatives/1.json
  def destroy
    @initiative.destroy
    respond_to do |format|
      format.html { redirect_to admin_initiatives_url, notice: 'Initiative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initiative
      @initiative = Initiative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def initiative_params
      params.require(:initiative).permit(:title, :description, :image, :active, :hashtag, :ngo_id)
    end
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  def index
    @ngo = Ngo.find(params[:ngo_id])
    @initiatives = @ngo.initiatives
  end

  def show
    @ngo = Ngo.find(params[:ngo_id])
    @initiative = @ngo.initiatives.find(params[:id])
    @signs_count = @initiative.signs.count
    @user_sign = @initiative.signs.of_user(current_user.id) if current_user
    @initiative_sign = InitiativeSign.new unless @user_sign
  end
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/views/initiatives/_form.html.erb
<%= form_for(@initiative) do |f| %>
  <% if @initiative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initiative.errors.count, "error") %> prohibited this initiative from being saved:</h2>

      <ul>
      <% @initiative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :hashtag %><br>
    <%= f.text_field :hashtag %>
  </div>
  <div class="field">
    <%= f.label :ngo_id %><br>
    <%= f.collection_select :ngo_id, Ngo.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/initiatives/_signs.html.erb
<div id="signs-count">
  Llevamos
  <%= content_tag :strong, @signs_count, data: { 'update-url' => count_initiative_sign_path(@initiative) } %>
  firma(s)
</div>
<% if @user_sign %>
  <p>Gracias por apoyar nuestra iniciativa, <%= current_user.first_name %></p>
<% else %>
  <h2>Tu firma respaldará nuestra iniciativa</h2>
  <% if @current_user %>
    <%= form_for(@initiative_sign, url: initiative_sign_path(@initiative), remote: true, data: {type: :html}) do |f| %>
      <p>Estás firmando como "<%= @current_user.first_name %>"</p>
      <%= f.label :message, 'Mensaje junto a tu firma (opcional)' %>
      <%= f.text_area :message, placeholder: 'Estoy firmando porque…' %>
      <div class="buttons">
        <%= f.submit :Firma %>
      </div>
    <% end %>
  <% else %>
    <p><%= link_to 'Inicia sesión', new_session_path %> para firmar.</p>
  <% end %>
<% end %>

app/views/initiatives/index.html.erb
<h1>Iniciativas de <%= @ngo.name %></h1>
<ul>
  <% @initiatives.each do |initiative| %>
    <li><%= link_to initiative.title, ngo_initiative_path(@ngo, initiative) %></li>
  <% end %>
</ul>

app/views/initiatives/new.html.erb
<h1>New Initiative</h1>

<%= render 'form' %>

<%= link_to 'Back', initiatives_path %>

app/views/initiatives/show.html.erb
<div id="initiative-container">
  <div id="initiative-content">
    <h1><%= @ngo.name %>: <%= @initiative.title %></h1>
    <h2>#<%= @initiative.hashtag %></h2>
    <p id="initiative-description">
      <%= image_tag 'placeholder.gif' %><%= @initiative.description %>
    </p>
  </div>
  <aside id="signs-container">
    <%= render partial: 'signs' %>
  </aside>
</div>